"""Add ollama_servers table

Revision ID: 52fc7eabb410
Revises: 20250904_183235
Create Date: 2025-09-05 01:40:06.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fc7eabb410'
down_revision: Union[str, None] = '20250904_183235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ollama_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_ollama_servers_id'), 'ollama_servers', ['id'], unique=False)
    
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_api_keys_key_prefix'))
        batch_op.create_unique_constraint('uq_api_keys_key_prefix', ['key_prefix'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint('uq_api_keys_key_prefix', type_='unique')
        batch_op.create_index(op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=True)

    op.drop_index(op.f('ix_ollama_servers_id'), table_name='ollama_servers')
    op.drop_table('ollama_servers')
    # ### end Alembic commands ###